services:
    Dbp\Relay\EsignBundle\Service\PdfAsApi:
        public: false
        autowire: true
        autoconfigure: true

    Dbp\Relay\EsignBundle\HealthCheck\HealthCheck:
        autowire: true
        autoconfigure: true

    Dbp\Relay\EsignBundle\Service\SignatureProviderInterface:
        '@Dbp\Relay\EsignBundle\Service\PdfAsApi'

    Dbp\Relay\EsignBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        autoconfigure: true

    Dbp\Relay\EsignBundle\State\:
        resource: '../../State'
        autowire: true
        autoconfigure: true

    Dbp\Relay\EsignBundle\Commands\:
        resource: '../../Commands'
        autowire: true
        autoconfigure: true

    Dbp\Relay\EsignBundle\Callbacks\:
        resource: '../../Callbacks'
        autowire: true
        autoconfigure: true
